// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL57PXOr1UD2LKP56BTsy9o6qk7LxQW14',
    appId: '1:502317486027:ios:77a54b929f112561aff04e',
    messagingSenderId: '502317486027',
    projectId: 'cicd-dev-90f52',
    storageBucket: 'cicd-dev-90f52.appspot.com',
    iosClientId:
        '502317486027-eum2kglkr24cb9tohf9os0dma4q5mf7m.apps.googleusercontent.com',
    iosBundleId: 'com.cicd.dev',
  );
}
