name: Build Upload iOS

on:
  push:
    braches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: "3.3.4"
      #     channel: "stable"
      # - name: Clean Flutter App
      #   run: flutter clean
      # - name: Install dependencies
      #   run: flutter pub get
      # - name: Run ios build
      #   run: flutter build ios --release --no-codesign
      # - name: Upload IPA
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-ipa
      #     path: build/ios/iphoneos/Runner.app
      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta_dev
          subdirectory: ios
        env:
          ITC_TEAM_ID: "${{ secrets.ITC_TEAM_ID }}"
          APPLICATON_ID: "${{ secrets.APPLICATION_ID_DEV }}"
          BUNDLE_IDENTIFIER: "${{ secrets.BUNDLE_IDENTIFIER_DEV }}"
          DEVELOPER_PORTAL_TEAM_ID: "${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}"
          FASTLANE_APPLE_ID: "${{ secrets.FASTLANE_APPLE_EMAIL_ID }}"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "${{ secrets.APP_SPECIFIC_PASSWORD }}"
          MATCH_PASSWORD: "${{ secrets.MATCH_PASSWORD }}"
          GIT_AUTHORIZATION: "${{ secrets.GIT_AUTHORIZATION }}"
          PROVISIONING_PROFILE_SPECIFIER: "${{ secrets.PROVISIONING_PROFILE_SPECIFIER_DEV }}"
          TEMP_KEYCHAIN_PASSWORD: "${{ secrets.TEMP_KEYCHAIN_PASSWORD }}"
          TEMP_KEYCHAIN_USER: "${{ secrets.TEMP_KEYCHAIN_USER }}"
